[workspace]
resolver = "2"
members = [
    "crates/wglymr-graph",
    "crates/wglymr-node-editor",
    "crates/wglymr-render-wgpu",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/krispy-snacc/wglymr"
