[package]
name = "wglymr-view"
version = "0.1.0"
edition = "2021"

[dependencies]
wglymr-document = { path = "../wglymr-document" }
wglymr-render = { path = "../wglymr-render" }
wglymr-color = { path = "../wglymr-color" }
glam = "0.29"
